export const editorPageStyles = {
  layout: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#ffffff",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
  },
  sidebar: {
    width: "260px",
    backgroundColor: "#f8f9fa",
    borderRight: "1px solid #e5e7eb",
    padding: "24px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    zIndex: 20,
  },
  sidebarBrand: {
    fontSize: "22px",
    fontWeight: "800",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#111827",
    padding: "0 8px",
    marginBottom: "10px",
  },
  menuSection: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  menuTitle: {
    fontSize: "11px",
    fontWeight: "700",
    color: "#9ca3af",
    letterSpacing: "1px",
    padding: "0 8px",
    marginBottom: "8px",
  },
  sidebarItem: {
    padding: "10px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    color: "#4b5563",
    fontWeight: "500",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sidebarItemActive: {
    padding: "10px 12px",
    borderRadius: "8px",
    backgroundColor: "#e0e7ff",
    color: "#3730a3",
    fontWeight: "600",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  icon: {
    fontSize: "18px",
  },
  mainArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  navbar: {
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    borderBottom: "1px solid #e5e7eb",
  },
  navLeft: {
    display: "flex",
    alignItems: "center",
  },
  docInfo: {
    display: "flex",
    flexDirection: "column",
  },
  docTitle: {
    fontSize: "18px",
    fontWeight: "600",
    margin: 0,
  },
  docStatus: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginTop: "4px",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    backgroundColor: "#10b981",
    borderRadius: "50%",
  },
  statusText: {
    fontSize: "12px",
    color: "#6b7280",
  },
  navRight: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  shareBtn: {
    backgroundColor: "#e0e7ff",
    color: "#4f46e5",
    border: "none",
    padding: "8px 16px",
    borderRadius: "20px",
    fontWeight: "600",
    cursor: "pointer",
    fontSize: "14px",
  },
  userBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "4px 12px 4px 4px",
    borderRadius: "30px",
    border: "1px solid #e5e7eb",
  },
  avatar: {
    width: "28px",
    height: "28px",
    backgroundColor: "#8b5cf6",
    color: "#fff",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
  },
  userName: {
    fontSize: "14px",
  },
  logoutBtn: {
    color: "#ef4444",
    border: "1px solid #fca5a5",
    backgroundColor: "#ffffff",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
  },
  workspace: {
    flex: 1,
    overflow: "auto",
    backgroundColor: "#f3f4f6",
  },
  editorContainer: {
    width: "100%",
    minHeight: "100%",
  },
  editorPaper: {
    padding: "40px 80px",
  },
};
